version: "3.8"
services:
  app:
    image: ${IMAGE}
    command: ./run
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    ports:
      - "8080:8080"
